#'''Parameters config.'''#


# --- binning_algorithms --- #

min_contig_len:   500


# --- metabat2_binning --- #

min_metabat_len:  1500


# --- concoct_binning --- #

fragment_size:    1500
overlap_size:     0


# --- vamb_binning --- #

min_bin_size: 100
# Test-only-values: '-e 2 -t 2 -q 1'
# Keep blank for actual runs
test_flags: '-e 2 -t 2 -q 1'


# --- semibin_binning --- #

model_environment: 'human_gut'


# --- maxbin2_binning --- #

maxbin2_script: '/home/lam4003/bin/MaxBin-2.2.7/run_MaxBin.pl'


# --- metabinner_binning --- #

metabinner_env: '/home/lam4003/bin/camp_binning/conda_envs/6de558979255c142cdea454d816f4b6a/'


# --- das_tool_refinement --- #

ext: '/home/lam4003/bin/camp_binning/workflow/ext'
