#'''Slurm job submission resource config.'''#


__default__:
    nCPU: 1
    mem: 8000
    output: "logs/{rule}/{wildcards}.out" # Wildcards are the most unconstrained therefore least findable
    # error: "logs/{rule}.{wildcards}.%j.err" # To redirect all STDOUT to the same file. Also removed in run_msw.sh
    job-name: "{rule}.{wildcards}.%j"


map_sort:
    mem : 20000
    nCPU: 5


metabat2_binning:
    mem : 80000
    nCPU: 20


concoct_binning:
    mem : 80000
